name: Publish Docker image
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          repository: ssaidali/demo/demo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true